package com.trading.journal.utility;

public class ProblemsSample {
/*
    @Data
    @Builder
    @AllArgsConstructor
    @NoArgsConstructor
    public class Problem {
        @Schema(description = "The type of the problem", example = "not-found")
        private String type;

        @Schema(description = "A short, human-readable summary of the problem", example = "Resource not found.")
        private String title;

        @Schema(description = "The HTTP status code generated by the origin server", example = "404")
        private int status;

        @Schema(description = "A URI reference that identifies the specific occurrence of the problem", example = "f7387427-b778-40e5-af80-403b5fcc7728")
        private String instance;

        @Schema(description = "A detailed explanation of the problem", example = "The resource specified was not found")
        private String detail;

        @Schema(description = "Additional information about the problem")
        private Extensions extensions;
    }

    @Data
    @Builder
    @AllArgsConstructor
    @NoArgsConstructor
    public class Extensions {
        @Schema(description = "A list of problems associated with the request")
        private List<Problems> problems;
    }

    @Data
    @Builder
    @AllArgsConstructor
    @NoArgsConstructor
    public class Problems {
        @Schema(description = "The name of the parameter", example = "parameterName")
        private String parameter;

        @Schema(description = "The description of the problem", example = "Invalid value provided")
        private String problem;

        @Schema(description = "The value submitted for the parameter", example = "12345")
        private String valueSubmitted;
    }*/
}
